import CheckoutForm from '@/components/CheckoutForm';

const features = [
  ['Airtight & leak-proof seal', 'Secure locking lids keep air out and freshness in, so soups, sauces, and liquids stay put.'],
  ['12-piece complete set', 'Four square, four round, and four rectangular containers cover meal prep, leftovers, snacks, and family meals.'],
  ['Premium borosilicate glass', 'A clean, non-porous surface does not absorb food smells or stain over time.'],
  ['Microwave, oven & freezer safe', 'Go straight from storage to reheating or cooking without switching containers.'],
  ['Save money on food waste', 'Keep meals fresher for longer instead of throwing away spoiled leftovers.'],
  ['BPA-free & food-safe', 'Store and reheat your food with confidence, without the concerns of plastic containers.'],
  ['Space-saving stackable design', 'The pieces stack neatly in your fridge, freezer, or cabinets to save space.'],
  ['Dishwasher safe & easy to clean', 'No staining, no lingering odors, and no scrubbing required after every meal.'],
];

const boxItems = ['4 square containers', '4 round containers', '4 rectangular containers', '12 airtight locking lids', 'Borosilicate glass', 'Freezer safe', 'Microwave safe', 'Dishwasher safe'];
const specs = [
  ['Set size', '12 pieces'],
  ['Sizes', '4 square, 4 round, 4 rectangular'],
  ['Material', 'Borosilicate glass'],
  ['Lid style', 'Four-clip airtight seal'],
  ['Use', 'Freezer, microwave, and dishwasher safe'],
  ['Capacity range', '150 ml to 1040 ml'],
  ['Delivery', 'Pay on delivery across Nigeria'],
];

function CheckIcon() {
  return <svg className="h-6 w-6 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9" strokeWidth="1.8" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.8" d="m8 12 2.5 2.5L16 9" /></svg>;
}

export default function PressurePage() {
  return (
    <div className="storefront">
      <header className="site-header"><div className="shell header-inner"><a className="logo" href="#top">TC <span>Store</span></a><nav className="site-nav" aria-label="Main navigation"><a href="#features">Features</a><a href="#sizes">Sizes</a><a href="#order">Order now</a></nav><a className="header-cta" href="#order">Get yours <span aria-hidden="true">↗</span></a></div></header>
      <main id="top">
        <section className="hero shell"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> TC Store kitchen essentials</p><h1>Keep your food fresh, organized &amp; <em>safe.</em></h1><p className="hero-lede">The 12-piece glass food storage container set keeps meals fresher for longer with airtight, leak-proof seals. No stains, no odors, no plastic worries.</p><div className="price-row"><span className="price">₦135,000</span><span className="old-price">₦180,000</span><span className="save-badge">Free delivery</span></div><a className="primary-button" href="#order">Shop now <span aria-hidden="true">→</span></a><div className="trust-row"><span>✓ Pay on delivery</span><span>✓ Nationwide delivery</span><span>✓ 1-year warranty</span></div></div><div className="hero-product"><div className="burst">12<br /><small>PIECES</small></div><img src="/glass-set-detail.jpg" alt="Glass food storage containers with airtight locking lids" /></div></section>
        <section className="product-video-section"><div className="shell"><div className="section-intro centered"><p className="eyebrow">See the set in your kitchen</p><h2>Organized storage, <em>made simple.</em></h2><p>See why these 12 pieces are the sizes you will actually reach for every day.</p></div><video className="product-video" controls playsInline preload="metadata"><source src="/glass-storage-video.mp4" type="video/mp4" />Your browser does not support the video element.</video></div></section>
        <section id="features" className="feature-band"><div className="shell"><div className="section-intro"><p className="eyebrow">Features</p><h2>Everything your kitchen needs for <em>better storage.</em></h2><p>Save money, eat healthier, and enjoy a beautifully organized kitchen with less effort every day.</p></div><div className="feature-grid">{features.map(([title, description]) => <article className="feature-card" key={title}><div className="feature-icon"><CheckIcon /></div><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section>
        <section className="review-section shell"><div className="section-intro centered"><p className="eyebrow">Reviews</p><h2>Loved by families across <em>Nigeria.</em></h2></div><div className="review-grid"><article><p>“My soups and stews stay fresh for days without leaking or smelling up the fridge. My kitchen finally looks organized.”</p><strong>Mrs. Funke Adeyemi</strong><span>Busy mum, Lagos</span></article><article><p>“I pack my kids&apos; lunches in them, reheat food straight in the microwave, and clean up takes seconds.”</p><strong>Mr. Emeka Okonkwo</strong><span>Father of three, Abuja</span></article><article><p>“They keep food fresh and stack neatly in my fridge. This set has become one of the best upgrades in my kitchen.”</p><strong>Mrs. Adaora Chukwu</strong><span>Port Harcourt</span></article></div></section>
        <section className="trust-section"><div className="shell"><div className="section-intro centered"><p className="eyebrow">Why order from us now?</p><h2>A safer, simpler way to <em>store food.</em></h2></div><div className="trust-grid"><article><strong>01</strong><h3>Trusted support</h3><p>Our customer care team stays available to guide and support you after you order.</p></article><article><strong>02</strong><h3>Free doorstep delivery</h3><p>We deliver straight to your doorstep at no extra cost across Nigeria.</p></article><article><strong>03</strong><h3>1-year warranty</h3><p>Your purchase is risk-free. Factory defects are covered by our warranty policy.</p></article><article><strong>04</strong><h3>Fast nationwide delivery</h3><p>Your set can arrive within 3 to 5 business days depending on your location.</p></article></div></div></section>
        <section id="sizes" className="specs-section shell"><div className="section-intro"><p className="eyebrow">Vital kitchen information</p><h2>Glass that fits<br /><em>real life.</em></h2><p>Store leftovers, prep lunches, and reheat meals in the same durable containers without stains, trapped smells, or a cupboard full of mismatched pieces.</p></div><div className="specs-table">{specs.map(([label, value]) => <div className="spec-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>
        <section id="how-it-works" className="how-section shell"><div className="section-intro centered"><p className="eyebrow">Simple from the first use</p><h2>From fridge to table<br /><em>in three steps.</em></h2></div><div className="steps-grid"><article><span>01</span><h3>Prep and store</h3><p>Choose the shape and size that fits your meal, then snap the lid closed.</p></article><article><span>02</span><h3>Reheat with ease</h3><p>Move the glass from freezer to microwave without transferring food to another dish.</p></article><article><span>03</span><h3>Clean and stack</h3><p>Put the set in the dishwasher, then stack the pieces neatly for the next meal.</p></article></div><div className="diagram-wrap"><img src="/glass-set-hero.jpg" alt="12-piece borosilicate glass food storage container set" /><div><p className="eyebrow">A closer look</p><h3>Clear, clean, and ready<br />for every meal.</h3><p>The non-porous glass surface helps keep food tasting fresh while the locking lids help prevent leaks.</p></div></div></section>
        <section className="video-feature video-feature-dark"><div className="shell video-feature-inner"><div className="video-feature-copy"><p className="eyebrow">Made for everyday storage</p><h2>Fresh food,<br /><em>less clutter.</em></h2><p>Three useful shapes give you a reliable place for leftovers, snacks, sauces, and full meals.</p></div><div className="video-card"><img src="/glass-set-lifestyle.jpg" alt="Glass food storage containers organized in a kitchen" /></div></div></section>
        <section className="box-section shell"><div className="box-image"><img src="/glass-set-box.jpg" alt="Complete 12-piece glass food storage set" /></div><div className="box-copy"><p className="eyebrow">Please check the sizes</p><h2>Here&apos;s what<br /><em>you receive.</em></h2><p>Our set contains practical sizes for storing family meals, leftovers, and snacks.</p><ul>{boxItems.map((item) => <li key={item}><span>+</span>{item}</li>)}</ul></div></section>
        <section className="health-section"><div className="shell"><div className="section-intro centered"><p className="eyebrow">Vital health information</p><h2>Why glass belongs in your kitchen, <em>not plastic.</em></h2></div><div className="health-grid"><article><img src="/glass-set-detail.jpg" alt="Clean glass containers with food" /><h3>No BPA, no hidden chemicals</h3><p>Borosilicate glass is a clean, non-porous material for storing and reheating meals with confidence.</p></article><article><img src="/glass-set-lifestyle.jpg" alt="Glass containers arranged in a kitchen" /><h3>No microplastics in your meals</h3><p>Glass does not break down or shed particles into food over time, even with repeated use.</p></article><article><img src="/glass-set-stack.jpg" alt="Stackable glass storage containers" /><h3>No stains, no trapped bacteria</h3><p>The smooth surface cleans completely every time, with no lingering odors from yesterday&apos;s meals.</p></article></div></div></section>
        <section className="video-feature video-feature-light"><div className="shell video-feature-inner"><div className="video-feature-copy"><p className="eyebrow">One more look</p><h2>Every piece<br /><em>has a place.</em></h2><p>Stack the shapes together, keep your fridge calm, and find the right container when you need it.</p></div><div className="video-card"><img src="/glass-set-stack.jpg" alt="Stacked glass food storage containers with lids" /></div></div></section>
        <section id="order" className="order-section"><div className="shell"><div className="order-heading"><p className="eyebrow">Order your glass containers today</p><h2>Place your order and enjoy<br /><em>free delivery nationwide.</em></h2><p>Pay only when it arrives. We&apos;ll call to confirm your delivery details.</p></div><div className="order-card"><CheckoutForm /></div></div></section>
      </main>
      <footer><div className="shell footer-inner"><a className="logo" href="#top">TC <span>Store</span></a><p>© 2026 TC Store Ltd · Pay on delivery across Nigeria</p></div></footer>
    </div>
  );
}